### ISSUE TITLE
Does this work on linux?

### ISSUE THREAD

**Issue by ghost** [walesey/binPipe#1]
When I try to compile with `make` in ubuntu 16.04, I get the following error:

```
main3D.c: In function ‘launchWindow’:
main3D.c:121:61: error: ‘GLUT_3_2_CORE_PROFILE’ undeclared (first use in this function)
   glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB | GLUT_DEPTH | GLUT_3_2_CORE_PROFILE);
                                                             ^
```

I have installed `freeglut3-dev` and have the `libgl1-mesa-dev` installed. Any other packages I need to compile?

**Comment by walesey** [comment]
Hey, Thanks for raising this!
I have added some code to resolve the compilation issue in linux.
freeglut still doesn't seem to work (program runs but you can't see anything)
I will continue to look at this issue.
Also feel free to raise a pull request if you would like to help 👍

**Comment by ghost** [comment]
Hi @walesey, Thanks for your response. It now compiles but actually crashes my whole system, interestingly not when running in a VM though. I'm wondering if you have instructions for how to build a debug version to step through in gdb?
